### ISSUE TITLE
Does not notice .mkv files playing

### ISSUE THREAD

**Issue by theblindhobo** [un-pogaz/Now-Playing-in-texts#1]
This extension is so great, thank you for all the work you've done! There's just one little issue I've noticed recently and that's the extension does not log or even realize when **.mkv** files are playing.

**Comment by un-pogaz** [comment]
Yes and No
NPT works for MKVs (Title, Artist name), but you were right: some MKVs don't work.
I'll look into this, but apparently it happens when a text is between brackets [] ... thats very common for some files coming from a particulars sources 😉

**Comment by theblindhobo** [comment]
Ah okay, thanks for the response!

**Comment by un-pogaz** [comment]
Okay, I upload a correctif, download the version of [`Now Playing in texts.lua`](https://github.com/un-pogaz/Now-Playing-in-texts/blob/main/Now%20Playing%20in%20texts.lua) and test on your side if is good (before a publish the release).

The bug was most vicious and big than I thought:
Is not the Title of MKV that bug (that was excessively specific and there was no reason for it to happen just in the MKV).
In fact, it is when the file name (or the file path) contained a text between brackets [] that bug, which means that ALL the files can be affected and could not be correctly read.
It comes from `vlc.net.url_parse()` (a VLC element) which incorrectly reads this type of file name, but a not sure. I will try to report the bug to them.

**Comment by theblindhobo** [comment]
Downloaded the updated version and everything seems to be working! I tried it with the couple .mkv files that wouldn't log before, and now they do.

Thank you for the speedy fix!

**Comment by un-pogaz** [comment]
Perfect.
Go publish the release.
