### ISSUE TITLE
Can't manage to make it work in Linux

### ISSUE THREAD

**Issue by Relf-Oc** [un-pogaz/Now-Playing-in-Texts#2]
Hi

I'm sorry to be a bother, but even with following the doc, I can't manage to get the files. Let me tell you everything I did and tried.

First on Linux, Ubuntu 20.04.
I downloaded the file, created the lua and extensions folders that were missing from within ~/.local/share/vlc/, copied the lua file in the extensions folder and THEN started vlc. (I checked the version : 3.0.9.2.) I started reading music. The music played, but no files were created in ~/.local/share/vlc/
I checked the rights, I seem to have all necessary rights. I went to the extension menu in vlc. "Now playing in texts" is listed, and appears as installed. Still nothing.
I restarted VLC. I even restarted the computer. Still nothing.

Secon try on MacOS Monterey 12.2.1 and VLC 3.0.16
I downloaded the file, created the lua and extensions folders that were missing from within /Users/%my_username%/Library/Application Support/org.videolan.vlc/, copied the lua file in the extensions folder and THEN started vlc.I started reading music. The music played, but no files were created in /Users/%my_usernam%/Library/Application Support/org.videolan.vlc/
And there it worked. I even could see the data in OBS.

However, Linux is my main OS and the only one I use to stream, so I would very much like to make it work there. Can you please help me ?

**Comment by un-pogaz** [comment]
Search on your computer "np_bandcamp.txt", I have copy/paste the Linux instruction from ohters Lua extension, so I am not sure where it creates the output TXT. Maybe it has changed or my info is incorrect.

If your click/initilize the lua extension but no TXT are create or no check mark appear next to him, please, give me a log file with `vlc --logfile="C:\Users\un_pogaz\AppData\Roaming\vlc\debug-lua.log" --file-logging --logmode=text --log-verbose=3` that I can look so that I can make sure that there is a problem _in the extension_ and possibly which one. _Outside the extension_, i'm not sure to be able to help you.

**Comment by tux-** [comment]
I had the same issue, and this is what is showing in my log:

lua debug: Scanning Lua script /home/username/.local/share/vlc/lua/extensions/Now Playing in Texts.lua
lua warning: Error loading script /home/username/.local/share/vlc/lua/extensions/Now Playing in Texts.lua: ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:255: invalid escape sequence near '\.'

**Comment by un-pogaz** [comment]
Thanks, with this I could find the problem.
Could you test this version of [Now Playing in Texts.lua](https://raw.githubusercontent.com/un-pogaz/Now-Playing-in-Texts/366ad04db13a6a757523e197f34b61ed9e7c9009/Now%20Playing%20in%20Texts.lua) to confirm if it works, thanks.

**Comment by tux-** [comment]
See ticket is closed. I am not sure what that new log message means, but, it is still not generating the files in Linux.

**Comment by un-pogaz** [comment]
You need to enlable the extension at least one time "View > Now Playing in Texts v2" to generate the files. If the check mark don't appear is that there is another subtlety/error specifice on Linux. (and a need log).

There, at the moment, I closed the ticket because the reported problem, "loading error: the extension don't appear in the menu", is solved.

**Comment by tux-** [comment]
Aha! When checking that button, it unchecks automatically, and this comes in the log:

qt debug: activating or triggering extension 'Now Playing in Texts v2'
lua debug: Activating extension 'Now Playing in Texts v2'
lua debug: [Now Playing texts] Activate {2.2}
lua debug: [Now Playing texts] init()
lua debug: [Now Playing texts] update_files()
lua debug: [Now Playing texts] write file > bandcamp
lua warning: Error while running script /home/username/.local/share/vlc/lua/extensions/Now Playing in Texts.lua, function activate(): ....local/share/vlc/lua/extensions/Now Playing in Texts.lua:284: attempt to call field 'getn' (a nil value)
lua error: Could not activate extension!
lua debug: Deactivating 'Now Playing in Texts v2'

**Comment by un-pogaz** [comment]
Okay, somehow, some lua functions are not identical between Windwos and Linux (in this case table.getn is deprecated)
As I'm under Windwos, it escaped me, now it's about checking all that. I may need you again because I can't find the list of Windwos/Linux differences, great.
[new test version](https://raw.githubusercontent.com/un-pogaz/Now-Playing-in-Texts/a78a3d2d6690b9511c03dee6dc912b1f63b5ab74/Now%20Playing%20in%20Texts.lua)

**Comment by tux-** [comment]
Heya, thanks again, that fixed it! Box is checked, and files are written, and they contain the expected information. Using VLC 3.0.9.2

**Comment by un-pogaz** [comment]
Hum, weird, I'm on VLC 3.0.17.4...

Oh well, whatever out what obscure stuff is going on behind the scenes, the main point is:
IT'S WORK!

Thank you for your time and help.
